version: "3.8"

services:
  backend:
    build:
      context: './backend'
    volumes:
      - './backend:/usr/app'
      - '/usr/app/node_modules'
    ports: 
      - 5000:5000
    environment: 
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DATABASE: postgres
      PG_HOST: db

  db:
    image: postgres:alpine3.16
    volumes:
      - book-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
      PG_USER: postgres

volumes: 
  book-postgres-data: