version: "3.8"

services:
  backend:
    image: hoangnguyenca/book-management-backend
    environment:
      PORT: 3000
      NODE_ENV: production
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DATABASE: postgres
      PG_HOST: db

  db:
    image: postgres:alpine3.16
    volumes:
      - book-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
      PG_USER: postgres

  nginx:
    restart: always
    build:
      context: "./nginx"
    ports:
      - 80:80

volumes:
  book-postgres-data:
