version: "3.8"

services:
  db:
    image: postgres:alpine3.16
    volumes:
      - book-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  

volumes: 
  book-postgres-data: